// Vendored IANA / WHATWG registry snapshots used by generated assertions and
// static lints. Values are lowercase for case-insensitive comparison.

/**
 * RFC 9209 Proxy-Status "HTTP Proxy Error Types" registry.
 * Snapshot of the initial RFC 9209 Section 2.3.2 contents (registry is
 * Specification Required, so unknown values downgrade to advisories).
 */
export const PROXY_STATUS_ERROR_TYPES: readonly string[] = [
  'dns_timeout',
  'dns_error',
  'destination_not_found',
  'destination_unavailable',
  'destination_ip_prohibited',
  'destination_ip_unroutable',
  'connection_refused',
  'connection_terminated',
  'connection_timeout',
  'connection_read_timeout',
  'connection_write_timeout',
  'connection_limit_reached',
  'tls_protocol_error',
  'tls_certificate_error',
  'tls_alert_received',
  'http_request_error',
  'http_request_denied',
  'http_response_incomplete',
  'http_response_header_section_size',
  'http_response_header_size',
  'http_response_body_size',
  'http_response_trailer_section_size',
  'http_response_trailer_size',
  'http_response_transfer_coding',
  'http_response_content_coding',
  'http_response_timeout',
  'http_upgrade_failed',
  'http_protocol_error',
  'proxy_internal_response',
  'proxy_internal_error',
  'proxy_configuration_error',
  'proxy_loop_detected'
];

/**
 * IANA "Well-Known URIs" registry suffixes (RFC 8615), permanent and
 * provisional entries. Snapshot taken 2026-07; used as a static lint, so an
 * unregistered suffix is a warning rather than a failure.
 */
export const WELL_KNOWN_URI_SUFFIXES: readonly string[] = [
  'acme-challenge',
  'amphtml',
  'api-catalog',
  'appspecific',
  'ashrae',
  'assetlinks.json',
  'broadband-labels',
  'brski',
  'caldav',
  'carddav',
  'change-password',
  'cmp',
  'core',
  'csaf',
  'csaf-aggregator',
  'csvm',
  'did.json',
  'did-configuration.json',
  'dnt',
  'dnt-policy.txt',
  'dots',
  'ecips',
  'edhoc',
  'enterprise-network-security',
  'enterprise-transport-security',
  'est',
  'genid',
  'gnap-as-rs',
  'gpc.json',
  'gs1resolver',
  'hoba',
  'host-meta',
  'host-meta.json',
  'hosting-provider',
  'http-opportunistic',
  'idp-proxy',
  'jmap',
  'keybase.txt',
  'knx',
  'looking-glass',
  'masque',
  'matrix',
  'mercure',
  'mta-sts.txt',
  'mud',
  'nfv-oauth-server-configuration',
  'ni',
  'nodeinfo',
  'nostr.json',
  'oauth-authorization-server',
  'oauth-protected-resource',
  'ohttp-gateway',
  'openid-configuration',
  'openid-federation',
  'openorg',
  'oslc',
  'pki-validation',
  'posh',
  'privacy-sandbox-attestations.json',
  'private-token-issuer-directory',
  'probing.txt',
  'pvd',
  'rd',
  'related-website-set.json',
  'reload-config',
  'repute-template',
  'resourcesync',
  'sbom',
  'security.txt',
  'ssf-configuration',
  'sshfp',
  'stun-key',
  'tdmrep.json',
  'terraform.json',
  'thread',
  'time',
  'timezone',
  'tor-relay',
  'tpcd',
  'traffic-advice',
  'trust.txt',
  'uma2-configuration',
  'void',
  'webfinger',
  'webweaver.json',
  'wot'
];

/**
 * Referrer-Policy closed enum (W3C Referrer Policy; the empty string is a
 * legal member of the comma-separated fallback list).
 */
export const REFERRER_POLICY_VALUES: readonly string[] = [
  '',
  'no-referrer',
  'no-referrer-when-downgrade',
  'same-origin',
  'origin',
  'strict-origin',
  'origin-when-cross-origin',
  'strict-origin-when-cross-origin',
  'unsafe-url'
];

/**
 * Fields that RFC 9110 Section 6.5.1 forbids in trailers: message framing,
 * routing, request modifiers (controls and conditionals), authentication,
 * response control data, and fields describing how to process the content.
 */
export const FORBIDDEN_TRAILER_FIELDS: readonly string[] = [
  'transfer-encoding',
  'content-length',
  'host',
  'cache-control',
  'expect',
  'max-forwards',
  'pragma',
  'range',
  'te',
  'if-match',
  'if-none-match',
  'if-modified-since',
  'if-unmodified-since',
  'if-range',
  'authorization',
  'proxy-authenticate',
  'proxy-authorization',
  'www-authenticate',
  'cookie',
  'set-cookie',
  'age',
  'expires',
  'date',
  'location',
  'retry-after',
  'vary',
  'warning',
  'content-encoding',
  'content-type',
  'content-range',
  'trailer'
];
