// Generation-time (static) contract validation for the built MCP EC collection.
//
// MCP EC items carry no test-script slot and the Postman CLI runner prunes
// `mcp-request`, so there is no runtime pm.test surface to instrument. The
// contract check is therefore performed here at generation time, mirroring the
// AsyncAPI module's discipline: every generated JSON-RPC message must be a
// well-formed JSON-RPC 2.0 request (a malformed one is a builder bug and fails
// closed), each tool's inputSchema is compiled and the synthesized tools/call
// arguments are validated against it (the MCP analogue of the OAS
// CONTRACT_EXAMPLE_SCHEMA_MISMATCH self-consistency check), server transport
// material is checked (sse url scheme, stdio command presence, no concrete
// secret values), item coverage is enforced, and the collection size gate is
// applied. No silent drops: anything not deterministically checkable emits an
// MCP_*-prefixed warning.

import { compileSchemaValidator } from '../../spec/schema-validator-code.js';
import { packSchema, isSchemaGraphOverflow } from '../../spec/schema-pack.js';
import type { McpContractIndex, McpServerDescriptor, McpToolDescriptor } from './mcp-parser.js';

type JsonRecord = Record<string, unknown>;

export interface McpInstrumentationResult {
  collection: JsonRecord;
  warnings: string[];
}

export const MCP_INSTRUMENT_LIMITS = {
  maxCollectionUpdateBytes: 4_000_000
} as const;

// MCP tool names: the registry/spec convention is a short programmatic
// identifier; anything outside this set still works on the wire but is flagged
// for auditability.
const TOOL_NAME_RE = /^[A-Za-z0-9_./-]{1,128}$/;

function asRecord(value: unknown): JsonRecord | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  return value as JsonRecord;
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

// JSON-RPC 2.0 request well-formedness (jsonrpc === '2.0', string method,
// string|number id, object params when present). The messages are generated by
// our own builder, so a violation is a generation bug: fail closed.
function assertJsonRpcRequest(message: unknown, itemTitle: string): void {
  const fail = (reason: string): never => {
    throw new Error(`MCP_MESSAGE_INVALID: item "${itemTitle}" carries a malformed JSON-RPC message (${reason}); generated MCP contract collection is invalid`);
  };
  if (typeof message !== 'string' || !message) fail('message is not a non-empty string');
  let parsed: unknown;
  try {
    parsed = JSON.parse(message as string);
  } catch {
    return fail('message is not valid JSON');
  }
  const record = asRecord(parsed);
  if (!record) return fail('message is not a JSON object');
  if (record.jsonrpc !== '2.0') return fail('jsonrpc must be the string "2.0"');
  if (typeof record.method !== 'string' || !record.method) return fail('method must be a non-empty string');
  if (typeof record.id !== 'string' && typeof record.id !== 'number') return fail('id must be a string or number');
  if (record.params !== undefined && asRecord(record.params) === null && !Array.isArray(record.params)) {
    return fail('params must be an object or array when present');
  }
}

function validateServer(server: McpServerDescriptor, warnings: string[]): void {
  if (server.transport === 'sse') {
    if (!server.url) {
      warnings.push(`MCP_SERVER_URL_MISSING: server ${server.id} declares a remote transport but no url; the generated request must be completed before use`);
    } else if (!/^https?:\/\//i.test(server.url)) {
      warnings.push(`MCP_SERVER_URL_INVALID: server ${server.id} remote url "${server.url}" is not an http(s) endpoint`);
    }
  } else if (!server.command) {
    warnings.push(`MCP_SERVER_COMMAND_MISSING: server ${server.id} declares a stdio transport but no launch command; the generated request must be completed before use`);
  }
  // Secret hygiene: env/header values that look like concrete credentials
  // (rather than {{variable}} placeholders) are flagged so no secret is
  // persisted into the collection.
  for (const entry of [...server.headers, ...server.env]) {
    const looksSecret = /(?:key|token|secret|password|credential)/i.test(entry.key);
    const isPlaceholder = /^\{\{[^}]+\}\}$/.test(entry.value) || entry.value === '';
    if (looksSecret && !isPlaceholder) {
      warnings.push(`MCP_SECRET_VALUE_PRESENT: server ${server.id} carries a concrete value for "${entry.key}"; replace it with a {{variable}} placeholder so the credential is not persisted in the collection`);
    }
  }
}

// MCP 2025-06-18 ToolAnnotations: the behavior hints are booleans and title is
// a string; a mis-typed hint is a manifest bug a client would misread.
const TOOL_ANNOTATION_BOOLEAN_HINTS = ['readOnlyHint', 'destructiveHint', 'idempotentHint', 'openWorldHint'] as const;

function validateToolAnnotations(tool: McpToolDescriptor, warnings: string[]): void {
  if (!tool.annotations) return;
  for (const hint of TOOL_ANNOTATION_BOOLEAN_HINTS) {
    const value = tool.annotations[hint];
    if (value !== undefined && typeof value !== 'boolean') {
      warnings.push(`MCP_TOOL_ANNOTATION_INVALID: tool ${tool.name} annotations.${hint} must be a boolean (MCP ToolAnnotations); got ${JSON.stringify(value)}`);
    }
  }
  if (tool.annotations.title !== undefined && typeof tool.annotations.title !== 'string') {
    warnings.push(`MCP_TOOL_ANNOTATION_INVALID: tool ${tool.name} annotations.title must be a string (MCP ToolAnnotations); got ${JSON.stringify(tool.annotations.title)}`);
  }
}

// MCP 2025-06-18: a tool that declares an outputSchema commits its tools/call
// results to carry structuredContent conforming to it, so the schema itself
// must be a compilable object schema. There is no runtime surface on
// mcp-request items, so conformance of live results stays out of scope; the
// deterministic generation-time contract is schema validity.
function validateToolOutputSchema(index: McpContractIndex, tool: McpToolDescriptor, warnings: string[]): void {
  if (!tool.outputSchema) return;
  const declaredType = tool.outputSchema.type;
  if (declaredType !== undefined && declaredType !== 'object') {
    warnings.push(`MCP_TOOL_OUTPUT_SCHEMA_INVALID: tool ${tool.name} outputSchema type is ${JSON.stringify(declaredType)}; the MCP specification requires tool output schemas to describe the structuredContent object`);
  }
  const packed = packSchema(index.documentJson, tool.outputSchema, '3.0', 'response');
  if (packed.unsupported) {
    const code = isSchemaGraphOverflow(packed) ? 'MCP_SCHEMA_NOT_COMPILED' : 'MCP_TOOL_OUTPUT_SCHEMA_NOT_VALIDATED';
    warnings.push(`${code}: tool ${tool.name} outputSchema is not validated (${packed.unsupported})`);
    return;
  }
  if (!compileSchemaValidator(packed.schema)) {
    warnings.push(`MCP_TOOL_OUTPUT_SCHEMA_NOT_VALIDATED: tool ${tool.name} outputSchema could not be compiled to a validator`);
  }
}

function validateTool(index: McpContractIndex, tool: McpToolDescriptor, warnings: string[]): void {
  if (!TOOL_NAME_RE.test(tool.name)) {
    warnings.push(`MCP_TOOL_NAME_UNCONVENTIONAL: tool name "${tool.name}" is outside the conventional [A-Za-z0-9_./-]{1,128} identifier set`);
  }
  validateToolAnnotations(tool, warnings);
  validateToolOutputSchema(index, tool, warnings);
  if (!tool.inputSchema) return;
  const declaredType = tool.inputSchema.type;
  if (declaredType !== undefined && declaredType !== 'object') {
    warnings.push(`MCP_TOOL_SCHEMA_INVALID: tool ${tool.name} inputSchema type is ${JSON.stringify(declaredType)}; the MCP specification requires tool input schemas to describe an object`);
  }
  const packed = packSchema(index.documentJson, tool.inputSchema, '3.0', 'request');
  if (packed.unsupported) {
    const code = isSchemaGraphOverflow(packed) ? 'MCP_SCHEMA_NOT_COMPILED' : 'MCP_TOOL_SCHEMA_NOT_VALIDATED';
    warnings.push(`${code}: tool ${tool.name} inputSchema is not validated (${packed.unsupported})`);
    return;
  }
  const validate = compileSchemaValidator(packed.schema);
  if (!validate) {
    warnings.push(`MCP_TOOL_SCHEMA_NOT_VALIDATED: tool ${tool.name} inputSchema could not be compiled to a validator`);
    return;
  }
  if (!validate(tool.sampleArguments)) {
    warnings.push(`MCP_TOOL_SAMPLE_MISMATCH: tool ${tool.name} synthesized tools/call arguments do not validate against the tool's own inputSchema; the generated template will not satisfy the contract`);
  }
}

export function instrumentMcpCollection(collection: JsonRecord, index: McpContractIndex): McpInstrumentationResult {
  const warnings: string[] = [
    ...index.warnings,
    ...index.servers.flatMap((server) => server.warnings),
    ...index.tools.flatMap((tool) => tool.warnings)
  ];

  for (const server of index.servers) validateServer(server, warnings);

  for (const tool of index.tools) validateTool(index, tool, warnings);

  // Coverage + message well-formedness over the built items: every server must
  // materialize initialize + tools/list + one tools/call per tool, each with a
  // distinct id and a well-formed JSON-RPC message. Fail closed on drift.
  const items = asArray(collection.item).map((entry) => asRecord(entry)).filter((entry): entry is JsonRecord => entry !== null);
  const ids: string[] = [];
  for (const item of items) {
    if (String(item.type) !== 'mcp-request') continue;
    ids.push(typeof item.id === 'string' && item.id ? item.id : `#${ids.length}`);
    assertJsonRpcRequest(asRecord(item.payload)?.message, String(item.title ?? item.id ?? 'mcp-request'));
  }
  const expected = index.servers.length * (2 + index.tools.length);
  const unique = new Set(ids).size;
  if (ids.length !== expected || unique !== expected) {
    throw new Error(
      `MCP_ITEM_COVERAGE_FAILED: built collection has ${ids.length} mcp-request item(s) (${unique} distinct) but the MCP index requires ${expected}; generated contract collection is incomplete or duplicated`
    );
  }

  const bytes = Buffer.byteLength(JSON.stringify(collection), 'utf8');
  if (bytes > MCP_INSTRUMENT_LIMITS.maxCollectionUpdateBytes) {
    throw new Error(`MCP_COLLECTION_SIZE_EXCEEDED: built MCP collection exceeded ${MCP_INSTRUMENT_LIMITS.maxCollectionUpdateBytes} bytes`);
  }

  return { collection, warnings: [...new Set(warnings)] };
}
